drop table if exists t_int32;
drop table if exists t_bigint;
drop table if exists t_real;
drop table if exists t_float;
drop table if exists t_double;
drop table if exists t_char;
drop table if exists t_vchar;
drop table if exists t_binary;
drop table if exists t_vbinary;
drop table if exists t_bool;
drop table if exists t_int32_char;
drop table if exists t_int32_vchar;
drop table if exists t_char_int32;
drop table if exists t_vchar_int32;
drop table if exists t_int32_int64;
drop table if exists t_float_double;
drop table if exists t_string_bytes;
drop table if exists t_string_bytes2;
drop table if exists t_bool_int32_string;
-- tablemake
create table t_int32 (v int);
create table t_bigint (v bigint);
create table t_real (v real);
create table t_float (v float);
create table t_double (v double);
create table t_char (v char(30));
create table t_vchar (v varchar);
create table t_binary (v binary(30));
create table t_vbinary (v varbinary);
create table t_bool (v int);
create table t_int32_char (v int, c char(30));
create table t_int32_vchar (v int, c varchar);
create table t_char_int32 (v char(30), c int);
create table t_vchar_int32 (v varchar, c int);
create table t_int32_int64 (v1 int, v2 bigint);
create table t_float_double (v1 float, v2 double);
create table t_string_bytes (v1 varchar, v2 varbinary);
create table t_string_bytes2 (v1 char(30), v2 binary(30));
create table t_bool_int32_string (v1 int, v2 int, v3 varchar);
-- insert
insert into t_int32 values (123);
insert into t_bigint values (1234567890123);
insert into t_real values (3.14);
insert into t_float values (1.23);
insert into t_double values (1.0e100);
insert into t_char values ('hello world');
insert into t_vchar values ('hello world');
insert into t_binary values (X'abcd');
insert into t_vbinary values (X'dcba');
insert into t_bool values (1);
insert into t_int32_char values (123, 'hello');
insert into t_int32_vchar values (456, 'world');
insert into t_char_int32 values ('hello',123);
insert into t_vchar_int32 values ('world',456);
insert into t_int32_int64 values (123, 1234567890123);
insert into t_float_double values (1.23, 1.0e100);
insert into t_string_bytes values ('hello', X'abcd');
insert into t_string_bytes2 values ('world', X'dcba');
insert into t_bool_int32_string values (1, 3, 'test');
-- check
select EchoInt32(v) from t_int32;
select EchoUInt32(v) from t_int32;
select EchoSInt32(v) from t_int32;
select EchoFixed32(v) from t_int32;
select EchoSFixed32(v) from t_int32;
select EchoInt64(v) from t_bigint;
select EchoUInt64(v) from t_bigint;
select EchoSInt64(v) from t_bigint;
select EchoFixed64(v) from t_bigint;
select EchoSFixed64(v) from t_bigint;
select EchoFloat(v) from t_float;
select EchoFloat(v) from t_float;
select EchoFloat(v) from t_real;
select EchoDouble(v) from t_double;
select EchoString(v) from t_char;
select EchoString(v) from t_vchar;
-- select EchoBytes(v) from t_binary;
-- select EchoBytes(v) from t_vbinary;
-- select BoolRequest(v) from t_bool;
select ConcatInt32String(v, c) from t_int32_char;
select ConcatInt32String(v, c) from t_int32_vchar;
select ConcatStringInt32(v, c) from t_char_int32;
select ConcatStringInt32(v, c) from t_vchar_int32;
select SumInt32Int64(v1, v2) from t_int32_int64;
select MultiplyFloatDouble(v1, v2) from t_float_double;
-- select CombineStringBytes(v1, v2) from t_string_bytes;
-- select CombineStringBytes(v1, v2) from t_string_bytes2;
-- select FormatBoolInt32String(v1, v2, v3) from t_bool_int32_string;
