# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blob_relay_local.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'blob_relay_local.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import blob_reference_pb2 as blob__reference__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62lob_relay_local.proto\x12 data_relay_grpc.blob_relay.proto\x1a\x14\x62lob_reference.proto\"\x18\n\x08\x42lobFile\x12\x0c\n\x04path\x18\x01 \x01(\t\"\xa3\x01\n\x0fGetLocalRequest\x12\x13\n\x0b\x61pi_version\x18\x01 \x01(\x04\x12\x14\n\nsession_id\x18\x02 \x01(\x04H\x00\x12\x18\n\x0etransaction_id\x18\x03 \x01(\x04H\x00\x12=\n\x04\x62lob\x18\x04 \x01(\x0b\x32/.data_relay_grpc.blob_relay.proto.BlobReferenceB\x0c\n\ncontext_id\"L\n\x10GetLocalResponse\x12\x38\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32*.data_relay_grpc.blob_relay.proto.BlobFile\"t\n\x0fPutLocalRequest\x12\x13\n\x0b\x61pi_version\x18\x01 \x01(\x04\x12\x12\n\nsession_id\x18\x02 \x01(\x04\x12\x38\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32*.data_relay_grpc.blob_relay.proto.BlobFile\"Q\n\x10PutLocalResponse\x12=\n\x04\x62lob\x18\x01 \x01(\x0b\x32/.data_relay_grpc.blob_relay.proto.BlobReference2\xec\x01\n\x0e\x42lobRelayLocal\x12l\n\x03Get\x12\x31.data_relay_grpc.blob_relay.proto.GetLocalRequest\x1a\x32.data_relay_grpc.blob_relay.proto.GetLocalResponse\x12l\n\x03Put\x12\x31.data_relay_grpc.blob_relay.proto.PutLocalRequest\x1a\x32.data_relay_grpc.blob_relay.proto.PutLocalResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blob_relay_local_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOBFILE']._serialized_start=82
  _globals['_BLOBFILE']._serialized_end=106
  _globals['_GETLOCALREQUEST']._serialized_start=109
  _globals['_GETLOCALREQUEST']._serialized_end=272
  _globals['_GETLOCALRESPONSE']._serialized_start=274
  _globals['_GETLOCALRESPONSE']._serialized_end=350
  _globals['_PUTLOCALREQUEST']._serialized_start=352
  _globals['_PUTLOCALREQUEST']._serialized_end=468
  _globals['_PUTLOCALRESPONSE']._serialized_start=470
  _globals['_PUTLOCALRESPONSE']._serialized_end=551
  _globals['_BLOBRELAYLOCAL']._serialized_start=554
  _globals['_BLOBRELAYLOCAL']._serialized_end=790
# @@protoc_insertion_point(module_scope)
