# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_relay_grpc/proto/blob_relay/blob_relay_streaming.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'data_relay_grpc/proto/blob_relay/blob_relay_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import blob_reference_pb2 as data__relay__grpc_dot_proto_dot_blob__relay_dot_blob__reference__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;data_relay_grpc/proto/blob_relay/blob_relay_streaming.proto\x12\x35\x64\x61ta_relay_grpc.proto.blob_relay.blob_relay_streaming\x1a\x35\x64\x61ta_relay_grpc/proto/blob_relay/blob_reference.proto\"\xb6\x01\n\x13GetStreamingRequest\x12\x13\n\x0b\x61pi_version\x18\x01 \x01(\x04\x12\x14\n\nsession_id\x18\x02 \x01(\x04H\x00\x12\x18\n\x0etransaction_id\x18\x03 \x01(\x04H\x00\x12L\n\x04\x62lob\x18\x04 \x01(\x0b\x32>.data_relay_grpc.proto.blob_relay.blob_reference.BlobReferenceB\x0c\n\ncontext_id\"\xce\x01\n\x14GetStreamingResponse\x12h\n\x08metadata\x18\x01 \x01(\x0b\x32T.data_relay_grpc.proto.blob_relay.blob_relay_streaming.GetStreamingResponse.MetadataH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x1a\x30\n\x08Metadata\x12\x13\n\tblob_size\x18\x01 \x01(\x04H\x00\x42\x0f\n\rblob_size_optB\t\n\x07payload\"\xf5\x01\n\x13PutStreamingRequest\x12g\n\x08metadata\x18\x01 \x01(\x0b\x32S.data_relay_grpc.proto.blob_relay.blob_relay_streaming.PutStreamingRequest.MetadataH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x1aY\n\x08Metadata\x12\x13\n\x0b\x61pi_version\x18\x01 \x01(\x04\x12\x12\n\nsession_id\x18\x02 \x01(\x04\x12\x13\n\tblob_size\x18\x03 \x01(\x04H\x00\x42\x0f\n\rblob_size_optB\t\n\x07payload\"d\n\x14PutStreamingResponse\x12L\n\x04\x62lob\x18\x01 \x01(\x0b\x32>.data_relay_grpc.proto.blob_relay.blob_reference.BlobReference2\xda\x02\n\x12\x42lobRelayStreaming\x12\xa0\x01\n\x03Get\x12J.data_relay_grpc.proto.blob_relay.blob_relay_streaming.GetStreamingRequest\x1aK.data_relay_grpc.proto.blob_relay.blob_relay_streaming.GetStreamingResponse0\x01\x12\xa0\x01\n\x03Put\x12J.data_relay_grpc.proto.blob_relay.blob_relay_streaming.PutStreamingRequest\x1aK.data_relay_grpc.proto.blob_relay.blob_relay_streaming.PutStreamingResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_relay_grpc.proto.blob_relay.blob_relay_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTREAMINGREQUEST']._serialized_start=174
  _globals['_GETSTREAMINGREQUEST']._serialized_end=356
  _globals['_GETSTREAMINGRESPONSE']._serialized_start=359
  _globals['_GETSTREAMINGRESPONSE']._serialized_end=565
  _globals['_GETSTREAMINGRESPONSE_METADATA']._serialized_start=506
  _globals['_GETSTREAMINGRESPONSE_METADATA']._serialized_end=554
  _globals['_PUTSTREAMINGREQUEST']._serialized_start=568
  _globals['_PUTSTREAMINGREQUEST']._serialized_end=813
  _globals['_PUTSTREAMINGREQUEST_METADATA']._serialized_start=713
  _globals['_PUTSTREAMINGREQUEST_METADATA']._serialized_end=802
  _globals['_PUTSTREAMINGRESPONSE']._serialized_start=815
  _globals['_PUTSTREAMINGRESPONSE']._serialized_end=915
  _globals['_BLOBRELAYSTREAMING']._serialized_start=918
  _globals['_BLOBRELAYSTREAMING']._serialized_end=1264
# @@protoc_insertion_point(module_scope)
