# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_relay_grpc/proto/blob_relay/blob_relay_local.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'data_relay_grpc/proto/blob_relay/blob_relay_local.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import blob_reference_pb2 as data__relay__grpc_dot_proto_dot_blob__relay_dot_blob__reference__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7data_relay_grpc/proto/blob_relay/blob_relay_local.proto\x12\x31\x64\x61ta_relay_grpc.proto.blob_relay.blob_relay_local\x1a\x35\x64\x61ta_relay_grpc/proto/blob_relay/blob_reference.proto\"\x18\n\x08\x42lobFile\x12\x0c\n\x04path\x18\x01 \x01(\t\"\xb2\x01\n\x0fGetLocalRequest\x12\x13\n\x0b\x61pi_version\x18\x01 \x01(\x04\x12\x14\n\nsession_id\x18\x02 \x01(\x04H\x00\x12\x18\n\x0etransaction_id\x18\x03 \x01(\x04H\x00\x12L\n\x04\x62lob\x18\x04 \x01(\x0b\x32>.data_relay_grpc.proto.blob_relay.blob_reference.BlobReferenceB\x0c\n\ncontext_id\"]\n\x10GetLocalResponse\x12I\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32;.data_relay_grpc.proto.blob_relay.blob_relay_local.BlobFile\"\x85\x01\n\x0fPutLocalRequest\x12\x13\n\x0b\x61pi_version\x18\x01 \x01(\x04\x12\x12\n\nsession_id\x18\x02 \x01(\x04\x12I\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32;.data_relay_grpc.proto.blob_relay.blob_relay_local.BlobFile\"`\n\x10PutLocalResponse\x12L\n\x04\x62lob\x18\x01 \x01(\x0b\x32>.data_relay_grpc.proto.blob_relay.blob_reference.BlobReference2\xb2\x02\n\x0e\x42lobRelayLocal\x12\x8e\x01\n\x03Get\x12\x42.data_relay_grpc.proto.blob_relay.blob_relay_local.GetLocalRequest\x1a\x43.data_relay_grpc.proto.blob_relay.blob_relay_local.GetLocalResponse\x12\x8e\x01\n\x03Put\x12\x42.data_relay_grpc.proto.blob_relay.blob_relay_local.PutLocalRequest\x1a\x43.data_relay_grpc.proto.blob_relay.blob_relay_local.PutLocalResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_relay_grpc.proto.blob_relay.blob_relay_local_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOBFILE']._serialized_start=165
  _globals['_BLOBFILE']._serialized_end=189
  _globals['_GETLOCALREQUEST']._serialized_start=192
  _globals['_GETLOCALREQUEST']._serialized_end=370
  _globals['_GETLOCALRESPONSE']._serialized_start=372
  _globals['_GETLOCALRESPONSE']._serialized_end=465
  _globals['_PUTLOCALREQUEST']._serialized_start=468
  _globals['_PUTLOCALREQUEST']._serialized_end=601
  _globals['_PUTLOCALRESPONSE']._serialized_start=603
  _globals['_PUTLOCALRESPONSE']._serialized_end=699
  _globals['_BLOBRELAYLOCAL']._serialized_start=702
  _globals['_BLOBRELAYLOCAL']._serialized_end=1008
# @@protoc_insertion_point(module_scope)
