# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import blob_relay_local_pb2 as data__relay__grpc_dot_proto_dot_blob__relay_dot_blob__relay__local__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in data_relay_grpc/proto/blob_relay/blob_relay_local_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BlobRelayLocalStub(object):
    """Transfer BLOB data over the file system.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/data_relay_grpc.proto.blob_relay.blob_relay_local.BlobRelayLocal/Get',
                request_serializer=data__relay__grpc_dot_proto_dot_blob__relay_dot_blob__relay__local__pb2.GetLocalRequest.SerializeToString,
                response_deserializer=data__relay__grpc_dot_proto_dot_blob__relay_dot_blob__relay__local__pb2.GetLocalResponse.FromString,
                _registered_method=True)
        self.Put = channel.unary_unary(
                '/data_relay_grpc.proto.blob_relay.blob_relay_local.BlobRelayLocal/Put',
                request_serializer=data__relay__grpc_dot_proto_dot_blob__relay_dot_blob__relay__local__pb2.PutLocalRequest.SerializeToString,
                response_deserializer=data__relay__grpc_dot_proto_dot_blob__relay_dot_blob__relay__local__pb2.PutLocalResponse.FromString,
                _registered_method=True)


class BlobRelayLocalServicer(object):
    """Transfer BLOB data over the file system.
    """

    def Get(self, request, context):
        """Download BLOB data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Upload BLOB data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlobRelayLocalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=data__relay__grpc_dot_proto_dot_blob__relay_dot_blob__relay__local__pb2.GetLocalRequest.FromString,
                    response_serializer=data__relay__grpc_dot_proto_dot_blob__relay_dot_blob__relay__local__pb2.GetLocalResponse.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=data__relay__grpc_dot_proto_dot_blob__relay_dot_blob__relay__local__pb2.PutLocalRequest.FromString,
                    response_serializer=data__relay__grpc_dot_proto_dot_blob__relay_dot_blob__relay__local__pb2.PutLocalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'data_relay_grpc.proto.blob_relay.blob_relay_local.BlobRelayLocal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('data_relay_grpc.proto.blob_relay.blob_relay_local.BlobRelayLocal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BlobRelayLocal(object):
    """Transfer BLOB data over the file system.
    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data_relay_grpc.proto.blob_relay.blob_relay_local.BlobRelayLocal/Get',
            data__relay__grpc_dot_proto_dot_blob__relay_dot_blob__relay__local__pb2.GetLocalRequest.SerializeToString,
            data__relay__grpc_dot_proto_dot_blob__relay_dot_blob__relay__local__pb2.GetLocalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data_relay_grpc.proto.blob_relay.blob_relay_local.BlobRelayLocal/Put',
            data__relay__grpc_dot_proto_dot_blob__relay_dot_blob__relay__local__pb2.PutLocalRequest.SerializeToString,
            data__relay__grpc_dot_proto_dot_blob__relay_dot_blob__relay__local__pb2.PutLocalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
