# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tsurugidb/udf/tsurugi_types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tsurugidb/udf/tsurugi_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!tsurugidb/udf/tsurugi_types.proto\x12\rtsurugidb.udf\"3\n\x07\x44\x65\x63imal\x12\x16\n\x0eunscaled_value\x18\x01 \x01(\x0c\x12\x10\n\x08\x65xponent\x18\x02 \x01(\x11\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61ys\x18\x01 \x01(\x11\"\x1a\n\tLocalTime\x12\r\n\x05nanos\x18\x01 \x01(\x12\"@\n\rLocalDatetime\x12\x16\n\x0eoffset_seconds\x18\x01 \x01(\x12\x12\x17\n\x0fnano_adjustment\x18\x02 \x01(\r\"[\n\x0eOffsetDatetime\x12\x16\n\x0eoffset_seconds\x18\x01 \x01(\x12\x12\x17\n\x0fnano_adjustment\x18\x02 \x01(\r\x12\x18\n\x10time_zone_offset\x18\x03 \x01(\x11\"X\n\rBlobReference\x12\x12\n\nstorage_id\x18\x01 \x01(\x04\x12\x11\n\tobject_id\x18\x02 \x01(\x04\x12\x0b\n\x03tag\x18\x03 \x01(\x04\x12\x13\n\x0bprovisioned\x18\x04 \x01(\x08\"X\n\rClobReference\x12\x12\n\nstorage_id\x18\x01 \x01(\x04\x12\x11\n\tobject_id\x18\x02 \x01(\x04\x12\x0b\n\x03tag\x18\x03 \x01(\x04\x12\x13\n\x0bprovisioned\x18\x04 \x01(\x08\x42\x13\n\x11\x63om.tsurugidb.udfb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tsurugidb.udf.tsurugi_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.tsurugidb.udf'
  _globals['_DECIMAL']._serialized_start=52
  _globals['_DECIMAL']._serialized_end=103
  _globals['_DATE']._serialized_start=105
  _globals['_DATE']._serialized_end=125
  _globals['_LOCALTIME']._serialized_start=127
  _globals['_LOCALTIME']._serialized_end=153
  _globals['_LOCALDATETIME']._serialized_start=155
  _globals['_LOCALDATETIME']._serialized_end=219
  _globals['_OFFSETDATETIME']._serialized_start=221
  _globals['_OFFSETDATETIME']._serialized_end=312
  _globals['_BLOBREFERENCE']._serialized_start=314
  _globals['_BLOBREFERENCE']._serialized_end=402
  _globals['_CLOBREFERENCE']._serialized_start=404
  _globals['_CLOBREFERENCE']._serialized_end=492
# @@protoc_insertion_point(module_scope)
