# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tsurugi_types_c4c2090500a0eacbc6950e80b7923136.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tsurugi_types_c4c2090500a0eacbc6950e80b7923136.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4tsurugi_types_c4c2090500a0eacbc6950e80b7923136.proto\x12\x13tsurugidb.udf.value\"3\n\x07\x44\x65\x63imal\x12\x16\n\x0eunscaled_value\x18\x01 \x01(\x0c\x12\x10\n\x08\x65xponent\x18\x02 \x01(\x11\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61ys\x18\x01 \x01(\x11\"\x1a\n\tLocalTime\x12\r\n\x05nanos\x18\x01 \x01(\x12\"@\n\rLocalDatetime\x12\x16\n\x0eoffset_seconds\x18\x01 \x01(\x12\x12\x17\n\x0fnano_adjustment\x18\x02 \x01(\r\"[\n\x0eOffsetDatetime\x12\x16\n\x0eoffset_seconds\x18\x01 \x01(\x12\x12\x17\n\x0fnano_adjustment\x18\x02 \x01(\r\x12\x18\n\x10time_zone_offset\x18\x03 \x01(\x11\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tsurugi_types_c4c2090500a0eacbc6950e80b7923136_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECIMAL']._serialized_start=77
  _globals['_DECIMAL']._serialized_end=128
  _globals['_DATE']._serialized_start=130
  _globals['_DATE']._serialized_end=150
  _globals['_LOCALTIME']._serialized_start=152
  _globals['_LOCALTIME']._serialized_end=178
  _globals['_LOCALDATETIME']._serialized_start=180
  _globals['_LOCALDATETIME']._serialized_end=244
  _globals['_OFFSETDATETIME']._serialized_start=246
  _globals['_OFFSETDATETIME']._serialized_end=337
# @@protoc_insertion_point(module_scope)
